[book]
authors = ["ritchie46"]
language = "en"
multilingual = false
src = "src"
title = "Polars - User Guide"

[output.html]
default-theme   = "Ayu"
mathjax-support = true
additional-css  = ["tabbed-code-blocks.css"]
additional-js   = ["tabbed-code-blocks.js"]

[output.html.fold]
enable = true
level = 1

# custom preprocessor to insert the reference guide links
[preprocessor.replace]
command = "python preprocessor/replace.py"
